trying to fix stray .d files when the compiler is interrupted

diff --git a/autoconf/bk-deps b/autoconf/bk-deps
--- a/autoconf/bk-deps
+++ b/autoconf/bk-deps
@@ -14,10 +14,8 @@ mkdir -p $DEPSDIR
 if test $DEPSMODE = gcc ; then
     $* ${DEPSFLAG}
     status=$?
-    if test ${status} != 0 ; then
-        exit ${status}
-    fi
-    # move created file to the location we want it in:
+
+    # determine location of created files:
     while test $# -gt 0; do
         case "$1" in
             -o )
@@ -34,6 +32,14 @@ if test $DEPSMODE = gcc ; then
     done
     depfile=`basename $srcfile | sed -e 's/\..*$/.d/g'`
     depobjname=`echo $depfile |sed -e 's/\.d/.o/g'`
+    
+    # if the compiler failed, we're done:
+    if test ${status} != 0 ; then
+        rm -f $depfile
+        exit ${status}
+    fi
+
+    # move created file to the location we want it in:
     if test -f $depfile ; then
         sed -e "s,$depobjname:,$objfile:,g" $depfile >${DEPSDIR}/${objfile}.d
         rm -f $depfile
